import React from 'react';
import { GameState } from '../types';

interface BaseDashboardProps {
  gameState: GameState;
  onUpgrade: () => void;
  canUpgrade: boolean;
  cost: number;
}

export const BaseDashboard: React.FC<BaseDashboardProps> = ({ gameState, onUpgrade, canUpgrade, cost }) => {
  return (
    <div className="absolute inset-0 bg-slate-950/95 z-40 flex flex-col items-center justify-center p-6">
      <h2 className="text-3xl font-bold text-white mb-6 border-b-2 border-cyan-500 pb-2">BASE COMMAND</h2>
      
      <div className="grid grid-cols-2 gap-8 w-full max-w-md mb-8">
        <div className="bg-slate-900 p-4 rounded border border-slate-700 text-center">
          <div className="text-4xl mb-2">🛡️</div>
          <div className="text-xl font-bold text-white">{gameState.baseHealth}/{gameState.baseMaxHealth}</div>
          <div className="text-xs text-slate-400">INTEGRITY</div>
        </div>
        <div className="bg-slate-900 p-4 rounded border border-slate-700 text-center">
          <div className="text-4xl mb-2">🏗️</div>
          <div className="text-xl font-bold text-white">LVL {gameState.baseLevel}</div>
          <div className="text-xs text-slate-400">FORTIFICATION</div>
        </div>
      </div>

      <div className="w-full max-w-md bg-slate-900 p-4 rounded border border-slate-800 mb-8 h-48 overflow-y-auto">
        <h3 className="text-xs text-cyan-500 font-bold mb-2">LOGS</h3>
        {gameState.logs.map((log, i) => (
          <p key={i} className="text-xs text-slate-300 font-mono mb-1 border-b border-slate-800 pb-1 last:border-0">
            {log}
          </p>
        ))}
      </div>

      <button
        onClick={onUpgrade}
        disabled={!canUpgrade}
        className="w-full max-w-md bg-emerald-700 hover:bg-emerald-600 disabled:opacity-30 disabled:cursor-not-allowed text-white font-bold py-4 rounded transition-all flex items-center justify-center gap-2"
      >
        <span>UPGRADE DEFENSES</span>
        <span className="text-xs bg-black/30 px-2 py-1 rounded">-{cost} WOOD</span>
      </button>

      <p className="mt-4 text-xs text-slate-500 text-center max-w-xs">
        Upgrade your base to reduce damage taken during the NIGHT PHASE events generated by Gemini AI.
      </p>
    </div>
  );
};